### ISSUE TITLE
Support spark to redshift via parquet s3 files

### ISSUE THREAD

**Issue by psvishnu91** [spark-redshift-community/spark-redshift#10]
Dataframes written to redshift are first copied to s3 in one of the following supported formats
* Avro
* CSV
* CSV GZIP

before being `COPY`ied to redshift. Redshift now supports ingesting data from parquet files. Would be a nice to have to support writing from parquet files to redshift since parquet has become the most widely adopted storage format for spark.

Amazon's announcement on supporting parquet files: https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-redshift-can-now-copy-from-parquet-and-orc-file-formats/

**Comment by Gauravshah** [comment]
why would parquet have any advantage ? also CSV is fastest in terms of speed

**Comment by psvishnu91** [comment]
Apologies. Yea in retrospect, I don't see a point in leveraging parquet while dumping data into redshift. Its storage vs access tradeoffs make little sense here.
