### ISSUE TITLE
Thread Safety Issue with makeTempPath in Utils.scala

### ISSUE THREAD

**Issue by dwilsonGW** [spark-redshift-community/spark-redshift#121]
In the Utils.scala the makeTempPath method updates a field variable lastTempPathGenerated which only exists for tests. However, in the event that the library is utilized by multiple threads this can cause the makeTempPath to return incorrect results. Tested out a simple fix in a forked repo to store the value to a local variable and return that instead of the field variable.

```
/**
   * Creates a randomly named temp directory path for intermediate data
   */
  def makeTempPath(tempRoot: String): String = {
    val _lastTempPathGenerated = Utils.joinUrls(tempRoot, UUID.randomUUID().toString)
    lastTempPathGenerated = _lastTempPathGenerated
    _lastTempPathGenerated
  }
```

**Comment by dwilsonGW** [comment]
@ylut 100% related to this issue. We're doing something very similar and that lead us to finding this issue.

**Comment by jsleight** [comment]
@dwilsonGW can you take your fix and submit it as a PR?  I'm happy to review and get it merged.

**Comment by dwilsonGW** [comment]
@jsleight sure thing
