### ISSUE TITLE
Change policy to 1 reviewer's approval

### ISSUE THREAD

**Issue by lucagiovagnoli** [spark-redshift-community/spark-redshift#14]
It looks like reviewers and commiters are pretty busy and the mandatory 2 approvals rule is significantly slowing down development. Can we change the policy to only require 1 reviewer's approval?
@smoy

**Comment by smoy** [comment]
I am cool with dropping this from 2 to 1 mandatory reviewer for now. We can re-visit this once we get more community members involved.

**Comment by smoy** [comment]
I have applied the change: Branch protection rule settings saved.
