### ISSUE TITLE
Use a dated s3temp folder name instead of using uuid

### ISSUE THREAD

**Issue by dongfeng3692** [spark-redshift-community/spark-redshift#145]
Sometimes I may want to use historical s3 files to restore redshift's historical data, but uuid makes it difficult for me to quickly find the version I want。

**Comment by bsharifi** [comment]
Thank you @smoy for the suggestion. Yes, a dated prefix can be added to the `tempdir` parameter like so and the uuid will be appended after it:
```
.option("tempdir", "s3n://mybucket/yyyy-mm-dd")
```
