### ISSUE TITLE
Print unloadSql and copySql statement

### ISSUE THREAD

**Issue by melin** [spark-redshift-community/spark-redshift#162]
Sometimes need to analyze task performance to see the generated sql pushdown conditions. redshift console is not easy to find

**Comment by bsharifi** [comment]
@melin, the connector does not log this information because it could contain sensitive customer information. However, there is a way to enable JDBC driver logging to Spark which will show the generated SQL statements (and other JDBC information):

```
val df = sqlContext.read
  .format("io.github.spark_redshift_community.spark.redshift")
  .options(rsOptions)
  **.option("jdbc.LogLevel", "6")
  .option("jdbc.LogPath", "/dev/stdout")**
  .option("dbtable", "MyTable")
  .load()
```
