### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by lucagiovagnoli** [spark-redshift-community/spark-redshift#19]
How to publish a scala project:
https://www.scala-sbt.org/1.x/docs/Publishing.html

Guide: https://maven.apache.org/repository/guide-central-repository-upload.html

Maven Central requirements:
https://central.sonatype.org/pages/requirements.html

**Comment by Gauravshah** [comment]
@lucagiovagnoli how can I help with this one ?

**Comment by lucagiovagnoli** [comment]
@Gauravshah, thanks a lot for offering. I added a few links on this process, it doesn't look very straightforward to me. I'm not sure when I'll have time to get to this. If you'd like to give this a go, I think the steps would be:
- satisfy the Central requirements: https://central.sonatype.org/pages/requirements.html
- follow the sbt guide: https://www.scala-sbt.org/1.x/docs/Publishing.html

I'd probably still need to do the credentials  pgp/gpg steps.

But let me know if you'd like to take a crack at this, I can review your PR.

**Comment by lucagiovagnoli** [comment]
I've created a JIRA ticket to initiate the request on Sonatype:
https://issues.sonatype.org/browse/OSSRH-51286

**Comment by lucagiovagnoli** [comment]
@Gauravshah I think I've managed to do this actually, I found a useful plugin to help: https://github.com/xerial/sbt-sonatype

Will update the PR soon

**Comment by Gauravshah** [comment]
thanks @lucagiovagnoli

**Comment by lucagiovagnoli** [comment]
I managed to publish a SNAPSHOT version here:

https://oss.sonatype.org/content/repositories/snapshots/io/github/spark-redshift-community/spark-redshift_2.11/4.0.0-SNAPSHOT/

Hopefully we will soon release a stable version.

**Comment by lucagiovagnoli** [comment]
This has been released! 
https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community

```
<dependency>
  <groupId>io.github.spark-redshift-community</groupId>
  <artifactId>spark-redshift_2.11</artifactId>
  <version>4.0.0</version>
</dependency>
```
