### ISSUE TITLE
Failed to find data source: com.databricks.spark.redshift [ spark-redshift_2.11-4.0.0.jar]

### ISSUE THREAD

**Issue by maimike** [spark-redshift-community/spark-redshift#32]
Hi 
actually when using the spark-redshift_2.11-4.0.0.jar, i always got the error Failed to find data source: com.databricks.spark.redshift but if i replace it to spark-redshift_2.11-3.0.0-preview1.jar (official), it work well except the error which brings me to this repo.

https://github.com/databricks/spark-redshift/issues/417

Link to get  spark-redshift_2.11-4.0.0.jar
https://search.maven.org/artifact/io.github.spark-redshift-community/spark-redshift_2.11/4.0.0/jar

**Comment by maimike** [comment]
Solve when using spark.read.format("io.github.spark_redshift_community.spark.redshift"). But could you please update the documents?
Thanks

**Comment by lucagiovagnoli** [comment]
Hi @maimike, is this similar to https://github.com/spark-redshift-community/spark-redshift/issues/17 ?

Could you please point me to the out of date docs ? If you mean the README, we kept the original README with the title "Original DataBricks Readme". If that's confusing, we could re-adapt it to show the updated groupId.

**Comment by JohnnyLVP** [comment]
Thanks @maimike , I could solve it with  with that

> Solve when using spark.read.format("io.github.spark_redshift_community.spark.redshift"). But could you please update the documents?
> Thanks
