### ISSUE TITLE
Getting `DateTimeParseException` error while reading from redshift timestamp.

### ISSUE THREAD

**Issue by hitesh-goel** [spark-redshift-community/spark-redshift#35]
```
java.time.format.DateTimeParseException: Text '2015-11-07 05:16:40.16858' could not be parsed, unparsed text found at index 23
```

**Comment by lucagiovagnoli** [comment]
Yes, this pattern `"yyyy-MM-dd HH:mm:ss[.SSS][.SS][.S][X]"` won't account for that.

Is that a real ISO-8601 datetime string ? 3 digits after the dot is ms, 6 digits is microseconds, what about 5 ?

**Comment by lucagiovagnoli** [comment]
The backend uses [Calendar](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#MILLISECOND), which won't go beyond milliseconds. Most of spark-redshift code is meant (and tested) not to go beyond milliseconds: https://github.com/spark-redshift-community/spark-redshift/blob/master/src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala#L48

This feature would mean more than just changing the format string. I'm available to review if anyone wants to take it on.

**Comment by eeshugerman** [comment]
@lucagiovagnoli do you have any suggestions for `Calendar` replacements?

Also (demonstrating my JVM ignorance here...), why is there no mention of `Calendar` in the source code? Instead I see a lot of `import java.sql.Timestamp` and `import java.time.format.DateTimeFormatter`. Do these standard library utils use `Calendar`?

**Comment by lucagiovagnoli** [comment]
Hey @eeshugerman, there are no basic questions, thanks for asking.

You're actually right, we're not using Calendar in the src/ code but only in tests to create fake data. The temporalAccessor and java.sql.Timestamp from Conversions.scala can both handle microseconds and nanoseconds.

I had a go at this in #51, feel free to review. Also for @smoy and @dichiarafrancesco

**Comment by eeshugerman** [comment]
Awesome, thanks for addressing this! I added a couple comments on the PR.
