### ISSUE TITLE
Jitpack Package Repository is using wrong group id

### ISSUE THREAD

**Issue by sniggel** [spark-redshift-community/spark-redshift#39]
How to reproduce:
1. Navigate to https://jitpack.io/
2. In the lookup search, type in: spark-redshift-community/spark-redshift and click "look up".
3. The group id for spark-redshift community is com.github.spark-redshift-community but should be io.github.spark-redshift-community

**Comment by smoy** [comment]
@lucagiovagnoli Do you have the creds to update jitpack.io entry?

**Comment by lucagiovagnoli** [comment]
I don't think so. I wonder how you can get those results by typing in `spark-redshift-community/spark-redshift` ?
We're currently uploading to https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community

**Comment by sniggel** [comment]
I am confused, clicking on this: https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community
shows 2 artefacts:
2.11 4.0.0
2.11 4.0.0-SNAPSHOT
There is another artefact called com.github.databricks/spark-redshift which is specified in the readme. What is this artefact ?: https://mvnrepository.com/artifact/com.github.databricks/spark-redshift

Also, I don't know if you tried compiling with 2.10 ? Seems only 2.11 is available, which would make sense I guess.

**Comment by sniggel** [comment]
Does jitpack is really necessary to fetch SNAPSHOT artifacts ?

**Comment by lucagiovagnoli** [comment]
I don't think we have release any SNAPSHOT artifacts, (maybe one) but you should find them on our [nexus](https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community).
We haven't uploaded anything to jitpack since the start of `spark-redshift-community`

**Comment by sniggel** [comment]
Alright, so I guess the snapshot section of the readme should be removed ?

**Comment by lucagiovagnoli** [comment]
It doesn't mean we will never release SNAPSHOTS in the future. Also if you check the link above, we actually have released 4.0.0-SNAPSHOT, you can find it on nexus.

**Comment by sniggel** [comment]
okay, so yes I do see the SNAPSHOT on nexus, however, maybe the jitpack resolver isn't needed in the README ?

**Comment by lucagiovagnoli** [comment]
Yes, I was thinking about removing it. Unless we plan on supporting jitpack @smoy  ?
