### ISSUE TITLE
Rename the organization and come up with a creative name

### ISSUE THREAD

**Issue by smoy** [spark-redshift-community/spark-redshift#5]
We got a confirmation from Reynold X. to do the following

> I think you guys should just fork it and create a new project. Our only asks are:
> 
> Acknowledge this came from the original Databricks package
> Clearly say that this is going to be different from the Databricks package
> Don't name the package spark-redshift to reduce confusion
>

**Comment by smoy** [comment]
1. spark-community-redshift
2. spark-open-redshift
3. spark-heart-redshift
4. spark-with-redshift
5. spark-knows-redshift

**Comment by sungjuly** [comment]
@smoy `spark-open-redshift` sounds good to me.

**Comment by smoy** [comment]
@andrewclegg @lucagiovagnoli any votes?

**Comment by davidmarin** [comment]
Hey all, I'm going to be helping Yelp port `spark-redshift` to Spark 2.4.

**Comment by davidmarin** [comment]
A couple of name suggestions:

If we want to be obvious, `spark-redshift-connector` is easy to parse.

If we want to be cute, how about `spark-doppler`?

**Comment by lucagiovagnoli** [comment]
I'd like to keep the words 'spark-redshift' close together as they are like a brand by now. 
I'd also like to communicate this is a welcoming community edition.

On the lines of what @smoy said, I'd suggest something like `spark-redshift-community` or `spark-redshift-open`

**Comment by davidmarin** [comment]
@lucagiovagnoli I agree.

`spark-redshift-for-all`?

**Comment by smoy** [comment]
> I'd like to keep the words 'spark-redshift' close together as they are like a brand by now.
> I'd also like to communicate this is a welcoming community edition.
> 
> On the lines of what @smoy said, I'd suggest something like `spark-redshift-community` or `spark-redshift-open`
> 
> Do we have restrictions on the organization name `spark-redshift` @smoy ?

Yes, we will be renaming the organization to the new name voted here, as long as its not "spark-redshift", i think we honor databrick's intend.

**Comment by smoy** [comment]
@sungjuly Would you vote for "spark-redshift-for-all"? We like to proceed to rename the organization.

**Comment by lucagiovagnoli** [comment]
I'd be happy with `spark-redshift-open` that is also similar to what @sungjuly suggested earlier (`spark-open-redshift`). Those 3 words re-arranged have been mentioned/voted on 3 times by @sungjuly @smoy and me previously.

**Comment by sungjuly** [comment]
@smoy @lucagiovagnoli actually I love `spark-redshift-community` more as @lucagiovagnoli suggested.

**Comment by lucagiovagnoli** [comment]
Works for me! If no one strongly opposes I'll go with that
