### ISSUE TITLE
spark-redshift breaks auto-broadcast?

### ISSUE THREAD

**Issue by eeshugerman** [spark-redshift-community/spark-redshift#55]
[original title: **Concurrency issues**]

-------

Hi,

So before this fork made use of `spark-redshift` feasible, I was using a roll-my-own version: writing and reading CSV files to S3 and using `psycopg2` to execute `copy` and `unload` queries. This solution had problems, and it's always preferable to **not** reinvent the wheel, but it was very fast. Upon switching to `spark-redshift`, my Spark job now takes 2-3 times as long, even when using `.option('tempformat', 'CSV')`. Further, the longest running stage looks like this in Spark History Server:
![image](https://user-images.githubusercontent.com/25518211/70356088-d63c6300-1830-11ea-9a69-f15bdc9a7ff5.png)

Whereas before it looked like this:
![image](https://user-images.githubusercontent.com/25518211/70356145-f8ce7c00-1830-11ea-8807-05d7b6f1d8d6.png)

Any insight? Is there a setting I need to adjust? Or is this an indication of an issue in `spark-redshift`?

Thanks!

**Comment by meetchandan** [comment]
Are you running the same queries with and without using `spark-redshift` ?

**Comment by eeshugerman** [comment]
Yes, I have not changed the queries.

**Comment by lucagiovagnoli** [comment]
@meetchandan thanks for opening this! It looks indeed very interesting.
It looks like spark-redshift could benefit from some performance improvements but I don't know of anyone at Yelp who noticed this (@smoy?), you might be in the best position to reproduce and debug this.

Please let us know if you find anything out!

**Comment by eeshugerman** [comment]
I've had a chance to revisit this, and turns out all that was needed to "fix" it was to force a broadcast of the smallest table in my join using `pyspark.sql.functions.broadcast`.

Any ideas as to why the broadcast doesn't happen automatically when using `spark-redshift`? The table is _very_ small (5 rows), and I haven't touched `spark.sql.autoBroadcastJoinThreshold`, so it should be at the default of 10mb.

Also there's another table in my join weighing in at about 1 mb, and I'm curious if it's being broadcasted automatically. Does anyone know how I can check?

**Comment by eeshugerman** [comment]
Also there's another table in the join weighing in at about 1 mb which previously was being auto-broadcasted, but isn't with `spark-redshift`.

**Comment by lucagiovagnoli** [comment]
Reading from this answer: https://stackoverflow.com/a/43984818
It seems that using `.broadcast()` hints overrides the default `autoBroadcastJoinThreshold`?

So I wonder if this line is the culprit: https://github.com/spark-redshift-community/spark-redshift/blob/master/src/main/scala/io/github/spark_redshift_community/spark/redshift/RedshiftFileFormat.scala#L78

I would try setting up a small test playing with configuration in the buildReader to see if it fixes it. Feel free to send us a PR to review!

**Comment by lucagiovagnoli** [comment]
Reading from this answer: https://stackoverflow.com/a/43984818
It seems that using `.broadcast()` hints overrides the default `autoBroadcastJoinThreshold`?

So I wonder if this line is the culprit: https://github.com/spark-redshift-community/spark-redshift/blob/master/src/main/scala/io/github/spark_redshift_community/spark/redshift/RedshiftFileFormat.scala#L78

I would try setting up a small test playing with configuration in the buildReader to see if it fixes it. Feel free to send us a PR to review!

**Comment by eeshugerman** [comment]
Thanks! I can give that a shot.

Also I just noticed this from the second answer in that StackOverflow thread:

>Note that currently statistics are only supported for Hive Metastore tables where the command ANALYZE TABLE  COMPUTE STATISTICS noscan has been run, and file-based data source tables where the statistics are computed directly on the files of data.

I've actually read this blurb several times by now, since it's in the documentation, but I think I just realized what it means: "statistics are only supported for..." means "Spark can only check the size of...". That is, Hive stuff aside, _autoBroadcast_ is only supported for "file-based data source tables where the statistics are computed directly on the files of data".

So perhaps, even though `spark-redshift` uses S3 files under the hood, it doesn't qualify as a "file-based data source" -- so what I'm seeing would actually be expected behaviour?

**Comment by lucagiovagnoli** [comment]
Thanks for looking into this!
Please let us know how you end up working around this problem, so we can have this information here for future reference

**Comment by eeshugerman** [comment]
Sure thing! My workaround is just to use broadcast hints, rather than relying on the autobroadcast feature.

I should been more clear: I'm closing this because I'm now pretty sure that what I described here is actually expected behaviour. See my previous comment for more information.
