### ISSUE TITLE
Wrong tag name for SNAPSHOT in jitpack

### ISSUE THREAD

**Issue by y-nosa** [spark-redshift-community/spark-redshift#67]
Currently, the release for the latest commit is named "-SNAPSHOT" in the jitpack, not the "master-SNAPSHOT" as mentioned in the documentation (https://jitpack.io/#spark-redshift-community/spark-redshift/-SNAPSHOT). I wonder, is it a time to make a new release just to reference more or less stable version instead of SNAPSHOT in the dependent projects.

**Comment by lucagiovagnoli** [comment]
Hi @y-nosa , apologies about the README. jitpack is a leftover from when we forked, we've already released a stable version "4.0.1", you can find it here: https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community

```
<dependency>
  <groupId>io.github.spark-redshift-community</groupId>
  <artifactId>spark-redshift_2.11</artifactId>
  <version>4.0.1</version>
</dependency>
```

Snapshots are on nexus too, you may find them here https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community

I'll update the README
