### ISSUE TITLE
Cross publish for scala 2.12

### ISSUE THREAD

**Issue by joprice** [spark-redshift-community/spark-redshift#71]
Any chance this could be cross-published for scala 2.12?

**Comment by lucagiovagnoli** [comment]
Hi @joprice,
feel free to send a PR over, I'm available to review

**Comment by ruturaj04** [comment]
Hey @joprice any ETA on seeing the finished product in master? :)

**Comment by potatochip** [comment]
+1

**Comment by lucagiovagnoli** [comment]
This is out:  https://search.maven.org/search?q=spark-redshift-community
