### ISSUE TITLE
Support AWS-KMS encryption for S3 files

### ISSUE THREAD

**Issue by alexmoore0** [spark-redshift-community/spark-redshift#82]
During an `UNLOAD` operation, Redshift natively performs server-side encryption for the files written to S3, however Redshift also supports specifying a KMS key ID to use for that encryption instead by adding a clause to the query:
`KMS_KEY_ID '<KMS_KEY_ID>' encrypted`.

[Redshift docs](https://docs.aws.amazon.com/redshift/latest/dg/t_unloading_encrypted_files.html)

Decrypting the KMS-encrypted files on read from S3 happens under-the-hood in AWS as long as the IAM profile used by the reader has access to the specified key. 

Proposal: add a new optional parameter `kms_key_id` that is passed down to the `UNLOAD` query.

**Comment by jsleight** [comment]
Seems like a reasonable proposal.  Interested in submitting a PR?

**Comment by alexmoore0** [comment]
@jsleight Yes, I have a branch off of `databricks/spark-redshift` that I can port over here and run the tests.

**Comment by jsleight** [comment]
Sounds great!
