### ISSUE TITLE
v5.0.0 not published to Maven

### ISSUE THREAD

**Issue by droher** [spark-redshift-community/spark-redshift#83]
It looks like v5 hasn't made it to Maven yet: https://mvnrepository.com/artifact/io.github.spark-redshift-community/spark-redshift

Would it be possible to add it? Thanks so much for maintaining this repo, it's a lifesaver!

**Comment by jsleight** [comment]
oops, sorry about that!  We'll try to get v5 published out this week 😄

**Comment by 88manpreet** [comment]
@droher Sorry for the delay. There were some access issues I faced today. I am planning to get this out first thing on the coming Monday.

**Comment by 88manpreet** [comment]
@lucagiovagnoli can you please provide access to me for the group `io.github.spark-redshift-community`. Ref.: [OSSRH-65648](https://issues.sonatype.org/browse/OSSRH-65648?focusedCommentId=1028982&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1028982)

**Comment by 88manpreet** [comment]
The latest version v5.0.3 is on Maven now: https://mvnrepository.com/artifact/io.github.spark-redshift-community/spark-redshift
Closing this issue.
