### ISSUE TITLE
NPE occurred while trying to read the S3 bucket lifecycle configuration

### ISSUE THREAD

**Issue by chaimturkel** [spark-redshift-community/spark-redshift#91]
rule.getStatus == BucketLifecycleConfiguration.ENABLED && key.startsWith(rule.getPrefix)

getPrefix is null, and method should use instead:  LifecycleFilter.

**Comment by jsleight** [comment]
Does #30 solve this?  We've been bad about merging that PR it seems... 😢

**Comment by 88manpreet** [comment]
@samuchoi I will work on getting the PR #30 merged.

**Comment by samuchoi** [comment]
Ok, thank you!

**Comment by 88manpreet** [comment]
@samuchoi please check the latest version for the fix.
 Let me know if the issue reproduces or re-open this issue.

**Comment by samuchoi** [comment]
@88manpreet thank you! Could the latest version be added to the maven central repository?

**Comment by YuelongCai** [comment]
@88manpreet This issue happened again with scala 2.12. Could you help release the latest version to maven central repository? Currently usage is compile group: 'io.github.spark-redshift-community', name: 'spark-redshift_2.12', version: '5.0.3' for gradle.
